In [1]:
import pandas as pd

path = "E:/Excel_course/Lesson No.15 - PowerPivot Table/Chatper 4 and 5-Practice File - Copy/Superstore Data For Date And Time Dax.xlsx"

df = pd.read_excel(path)

print("Excel file loaded successfully!")

Excel file loaded successfully!

first 10 rows

In [2]:
df.head(10)

,Unnamed: 0.1,Unnamed: 0,Row ID,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Price/Unit,Quantity
0,0,0,1,CA-2016-152156,2016-08-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3
1,1,1,2,CA-2016-152156,2016-08-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,1
2,2,2,3,CA-2016-138688,2016-12-06 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2
3,3,3,4,US-2015-108966,2015-11-10 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,4
4,4,4,5,US-2015-108966,2015-11-10 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,1
5,5,5,6,CA-2014-115812,2014-09-06 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,4
6,6,6,7,CA-2014-115812,2014-09-06 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,3
7,7,7,8,CA-2014-115812,2014-09-06 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,1
8,8,8,9,CA-2014-115812,2014-09-06 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,2
9,9,9,10,CA-2014-115812,2014-09-06 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,1

next code here , next time to see

last 10 rows

In [3]:
df.tail(10)

,Unnamed: 0.1,Unnamed: 0,Row ID,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Price/Unit,Quantity
9984,9984,9984,9985,CA-2015-100251,5/17/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,New York,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.500,2
9985,9985,9985,9986,CA-2015-100251,5/17/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,New York,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.600,2
9986,9986,9986,9987,CA-2016-125794,9/29/2016,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,California,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,4
9987,9987,9987,9988,CA-2017-163629,11/17/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,Georgia,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.990,1
9988,9988,9988,9989,CA-2017-163629,11/17/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,Georgia,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,1
9989,9989,9989,9990,CA-2014-110422,1/21/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,4
9990,9990,9990,9991,CA-2017-121258,2/26/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,4
9991,9991,9991,9992,CA-2017-121258,2/26/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2
9992,9992,9992,9993,CA-2017-121258,2/26/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,2
9993,9993,9993,9994,CA-2017-119914,2017-04-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,4

save the file

In [4]:
df.to_excel(path) # save the file

In [5]:
df.dtypes  # see data type

Unnamed: 0.1       int64
Unnamed: 0         int64
Row ID             int64
Order ID             str
Order Date        object
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Price/Unit       float64
Quantity           int64
dtype: object

In [6]:
df.describe(include="all")

,Unnamed: 0.1,Unnamed: 0,Row ID,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Price/Unit,Quantity
count,9994.000000,9994.000000,9994.000000,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994.000000,9994,9994,9994,9994,9994,9994.000000,9994.000000
unique,NaN,NaN,NaN,5009,1237,4,793,793,3,1,531,49,NaN,4,1862,3,17,1850,NaN,NaN
top,NaN,NaN,NaN,CA-2017-100111,2016-05-09 00:00:00,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN
freq,NaN,NaN,NaN,14,38,5968,37,37,5191,9994,915,2001,NaN,3203,19,6026,1523,48,NaN,NaN
mean,4996.500000,4996.500000,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55190.379428,NaN,NaN,NaN,NaN,NaN,229.858001,2.513808
std,2885.163629,2885.163629,2885.163629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32063.693350,NaN,NaN,NaN,NaN,NaN,623.245101,1.119257
min,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1040.000000,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000
25%,2498.250000,2498.250000,2499.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000
50%,4996.500000,4996.500000,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56430.500000,NaN,NaN,NaN,NaN,NaN,54.490000,3.000000
75%,7494.750000,7494.750000,7495.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90008.000000,NaN,NaN,NaN,NaN,NaN,209.940000,4.000000
max,9993.000000,9993.000000,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,4.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0.1   9994 non-null   int64
 1   Unnamed: 0     9994 non-null   int64
 2   Row ID         9994 non-null   int64
 3   Order ID       9994 non-null   str
 4   Order Date     9994 non-null   object
 5   Ship Mode      9994 non-null   str
 6   Customer ID    9994 non-null   str
 7   Customer Name  9994 non-null   str
 8   Segment        9994 non-null   str
 9   Country        9994 non-null   str
 10  City           9994 non-null   str
 11  State          9994 non-null   str
 12  Postal Code    9994 non-null   int64
 13  Region         9994 non-null   str
 14  Product ID     9994 non-null   str
 15  Category       9994 non-null   str
 16  Sub-Category   9994 non-null   str
 17  Product Name   9994 non-null   str
 18  Price/Unit     9994 non-null   float64
 19  Quantity       9994 non-null   int64
dtypes: float64(1), int64(5), object(1), str(13)
memory usage: 3.1+ MB

In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Row ID', 'Order ID', 'Order Date',
       'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country',
       'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Price/Unit', 'Quantity'],
      dtype='str')

In [9]:
# import pandas as pd

# path =  "E:/Excel_course/Lesson No.15 - PowerPivot Table/Chatper 4 and 5-Practice File - Copy/Superstore Data For Date And Time Dax.xlsx"
# df = pd.read_excel(path)
# print(df)

In [10]:
df

,Unnamed: 0.1,Unnamed: 0,Row ID,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Price/Unit,Quantity
0,0,0,1,CA-2016-152156,2016-08-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3
1,1,1,2,CA-2016-152156,2016-08-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,1
2,2,2,3,CA-2016-138688,2016-12-06 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2
3,3,3,4,US-2015-108966,2015-11-10 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,4
4,4,4,5,US-2015-108966,2015-11-10 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9989,9989,9990,CA-2014-110422,1/21/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,4
9990,9990,9990,9991,CA-2017-121258,2/26/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,4
9991,9991,9991,9992,CA-2017-121258,2/26/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2
9992,9992,9992,9993,CA-2017-121258,2/26/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,2
9993,9993,9993,9994,CA-2017-119914,2017-04-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,4