In [4]:
import pandas as pd
path = "E:/Excel_course/aman_45.xlsx"
df = pd.read_excel(path)
print(df)

  Name of Student  Sub1  Sub2  Sub3 Result       %Age Only Grade Grade
0               A    95    98    90   Pass  94.333333        A++    A++
1               B    36    42    35   Pass  37.666667          C      C
2               C    70    65    80   Pass  71.666667          A      A
3               D    35    55    73   Pass  54.333333          B      B
4               E    28    88    87   Fail  67.666667          A   Fail

In [5]:
df.head(5)

  Name of Student  Sub1  Sub2  Sub3 Result       %Age Only Grade Grade
0               A    95    98    90   Pass  94.333333        A++    A++
1               B    36    42    35   Pass  37.666667          C      C
2               C    70    65    80   Pass  71.666667          A      A
3               D    35    55    73   Pass  54.333333          B      B
4               E    28    88    87   Fail  67.666667          A   Fail

In [7]:
headers = ["student_name", "num1", "num2", "num3","F_ruselt", "%Age", "only grade", "grade"]
df.columns = headers
df.head(5)

  student_name  num1  num2  num3 F_ruselt       %Age only grade grade
0            A    95    98    90     Pass  94.333333        A++   A++
1            B    36    42    35     Pass  37.666667          C     C
2            C    70    65    80     Pass  71.666667          A     A
3            D    35    55    73     Pass  54.333333          B     B
4            E    28    88    87     Fail  67.666667          A  Fail

num1 ke row me one add (+)

In [8]:
df["num1"]=df["num1"]+1

In [9]:
df.head(5)

  student_name  num1  num2  num3 F_ruselt       %Age only grade grade
0            A    96    98    90     Pass  94.333333        A++   A++
1            B    37    42    35     Pass  37.666667          C     C
2            C    71    65    80     Pass  71.666667          A     A
3            D    36    55    73     Pass  54.333333          B     B
4            E    29    88    87     Fail  67.666667          A  Fail

In [ ]:
df["num1"] = df["num1"] /2  # num1 is divide by 2

In [11]:
print(df)

  student_name  num1  num2  num3 F_ruselt       %Age only grade grade
0            A  48.0    98    90     Pass  94.333333        A++   A++
1            B  18.5    42    35     Pass  37.666667          C     C
2            C  35.5    65    80     Pass  71.666667          A     A
3            D  18.0    55    73     Pass  54.333333          B     B
4            E  14.5    88    87     Fail  67.666667          A  Fail

In [14]:
df.rename(columns={"num1":"num1/2"}, )  # change columns name num1 to num1/2

  student_name  num1/2  num2  num3 F_ruselt       %Age only grade grade
0            A    48.0    98    90     Pass  94.333333        A++   A++
1            B    18.5    42    35     Pass  37.666667          C     C
2            C    35.5    65    80     Pass  71.666667          A     A
3            D    18.0    55    73     Pass  54.333333          B     B
4            E    14.5    88    87     Fail  67.666667          A  Fail

In [15]:
df.dtypes   # cheack data types

student_name        str
num1            float64
num2              int64
num3              int64
F_ruselt            str
%Age            float64
only grade          str
grade               str
dtype: object

In [ ]:
df["num1"]=df["num1"].astype("int")    # change data type  float to int 
print(df)

  student_name  num1  num2  num3 F_ruselt       %Age only grade grade
0            A    48    98    90     Pass  94.333333        A++   A++
1            B    18    42    35     Pass  37.666667          C     C
2            C    35    65    80     Pass  71.666667          A     A
3            D    18    55    73     Pass  54.333333          B     B
4            E    14    88    87     Fail  67.666667          A  Fail